/**
 * Mocks of the Steam wishlist page, in both layouts the userscripts have to
 * cope with.
 *
 * `currentLayout()` is the page as Steam rewrote it: the list is virtualized —
 * about sixteen rows of a wishlist of any length are in the markup at once —
 * the class names are generated by a bundler and change by themselves, and the
 * one stable anchor is `data-rfd-draggable-id`, holding
 * `WishlistItem-<app id>-<number in the list>`. Nothing scrolls except a
 * container far above the rows.
 *
 * `oldLayout()` is the page as it was: `.wishlist_row` elements with
 * `id="wishlist_row_<app id>"`, absolutely positioned inside `#wishlist_ctn`,
 * numbered nowhere. It is here so that the fallbacks stay honest — a user may
 * still be served that page, and the selectors for it are not to be broken by a
 * change made for the new one.
 *
 * The rows carry no wishlist data of anybody's: the app ids are made up from a
 * base, and the titles say so.
 */

import { createDocument, el } from './dom.js';

/** Where the made-up app ids start. */
export const APP_ID_BASE = 294100;

/**
 * The app id of the row that stands at a given place in the list.
 *
 * @param {number} index
 * @returns {number}
 */
export function appIdAt(index) {
  return APP_ID_BASE + index;
}

/**
 * One row of the current layout: obfuscated classes, a link to the store, a
 * capsule, and the drag and drop anchor that carries the app id and the number.
 *
 * @param {number} index
 * @param {{ draggableId?: string|null, dlc?: boolean, appId?: number }} [options]
 * @returns {object}
 */
function currentRow(index, { draggableId, dlc = false, appId = appIdAt(index), top = index * 69 } = {}) {
  const attributes = { class: 'S2Q8eqrNOA4- _1Rc0Q3', $top: top, $height: 69 };
  const anchor = draggableId === undefined ? `WishlistItem-${appId}-${index}` : draggableId;
  if (anchor !== null) attributes['data-rfd-draggable-id'] = anchor;

  const children = [
    el('img', {
      class: 'kYq2n1pA0Xs-',
      src: `https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/${appId}/capsule_231x87.jpg`,
      alt: `Sample game ${index + 1}`,
    }),
    el('a', { class: 'Zb9K0-', href: `/app/${appId}/` }, [el('span', { class: 'q7Yb-', $text: `Sample game ${index + 1}` })]),
  ];
  if (dlc) children.push(el('span', { class: 'mNn4v-', $text: 'DLC' }));

  return el('div', attributes, children);
}

/**
 * The made-up account the mock pages belong to. Seventeen digits, and the
 * account of nobody: Steam ids of real people are not written into this repo.
 */
export const OWNER_STEAM_ID = '76561198000000001';

/** A second one, for the pages that name two accounts and must be refused. */
export const OTHER_STEAM_ID = '76561198000000002';

/**
 * The bits of a page that say whose wishlist it is, each of them separately.
 *
 * Every option is one source of the chain and nothing else, so a test can build
 * a page that carries exactly one of them — which is the only way to tell that
 * the source under test is the one that answered.
 *
 * @param {{ gSteamID?: string|null, profileLinks?: string[],
 *           scriptAddresses?: string[], dataSteamIds?: string[], junk?: boolean }} [options]
 *   `gSteamID` is the variable of the old layout, written into a script the way
 *   Steam wrote it. `scriptAddresses` are numeric wishlist addresses inside an
 *   inline script — what the rewritten page actually carries. `junk` adds ids
 *   of the wrong shape everywhere, which are to be picked up by nothing.
 * @returns {object[]}
 */
export function ownerMarkup({
  gSteamID = null,
  profileLinks = [],
  scriptAddresses = [],
  dataSteamIds = [],
  junk = false,
} = {}) {
  const nodes = [];

  if (gSteamID !== null) {
    nodes.push(el('script', { $text: `var g_sessionID = "b6f2c1d4e5a60718"; var g_steamID = "${gSteamID}";` }));
  }
  for (const steamId of profileLinks) {
    nodes.push(
      el('a', { class: 'Nn2v-', href: `/wishlist/profiles/${steamId}/` }, [el('span', { $text: 'Wishlist' })]),
    );
  }
  for (const steamId of scriptAddresses) {
    nodes.push(
      el('script', {
        $text:
          '(function(){window.__PRELOADED__={"canonical":' +
          `"https://store.steampowered.com/wishlist/profiles/${steamId}/","rgWishlist":[]};}())`,
      }),
    );
  }
  for (const steamId of dataSteamIds) {
    nodes.push(el('div', { class: 'playerAvatar', 'data-steamid': steamId }));
  }

  if (junk) {
    // Everything here is the right shape at a glance and the wrong one on a
    // count: sixteen digits, eighteen, letters, an empty attribute.
    nodes.push(
      el('a', { href: '/wishlist/profiles/7656119800000000/' }),
      el('a', { href: '/wishlist/profiles/765611980000000012/' }),
      el('script', { $text: 'var g_steamID = "not-an-id"; /* wishlist/profiles/12345/ */' }),
      el('div', { 'data-steamid': 'abcdefghijklmnopq' }),
      el('div', { 'data-steamid': '' }),
    );
  }

  return nodes;
}

/**
 * The wishlist page as it is now.
 *
 * @param {{ indexes?: number[], dlcIndexes?: number[], draggableIds?: Record<number, string|null>,
 *           scrollerId?: string|null, scrollHeight?: number, clientHeight?: number,
 *           decoy?: boolean, stackFromTop?: boolean, owner?: object|null }} [options]
 *   `indexes` are the places whose rows are in the markup right now — a
 *   virtualized list renders a window, not the list. `scrollerId` set to `null`
 *   leaves the scrolling container with nothing but a generated class name,
 *   which is what the next redesign looks like from here. `decoy` adds a second
 *   scrolling element that matches a known selector but holds no rows. `owner`
 *   is handed to `ownerMarkup()` and says what the page states about the
 *   account it belongs to; left out, the page states nothing — which is the
 *   page Steam serves.
 * @returns {{ document: object, scroller: object, rows: object[] }}
 */
export function currentLayout({
  indexes = Array.from({ length: 16 }, (_, index) => index),
  dlcIndexes = [],
  draggableIds = {},
  scrollerId = 'StoreTemplate',
  scrollHeight = 11_454,
  clientHeight = 720,
  decoy = false,
  stackFromTop = false,
  owner = null,
} = {}) {
  const rows = indexes.map((index, position) =>
    currentRow(index, {
      dlc: dlcIndexes.includes(index),
      draggableId: index in draggableIds ? draggableIds[index] : undefined,
      // A virtualized list reuses the same handful of positioned nodes, so the
      // rows of the window it renders can sit at the very same coordinates the
      // previous window sat at. `stackFromTop` is that page.
      top: stackFromTop ? position * 69 : index * 69,
    }),
  );

  const list = el('div', { class: 'Vp3M9zQ-' }, rows);
  const scrollerAttributes = { class: 'S2Q8eqrNOA4- _0Wm2', $scrollHeight: scrollHeight, $clientHeight: clientHeight };
  if (scrollerId !== null) scrollerAttributes.id = scrollerId;
  const scroller = el('div', scrollerAttributes, [el('div', { class: 'hHm1x-' }, [list])]);

  const children = [scroller];
  if (decoy) {
    // Scrolls, matches a selector the script knows, and has nothing to do with
    // the wishlist. Taking it would scroll a sidebar and load no rows at all.
    children.unshift(
      el('div', { id: 'page_content', $scrollHeight: 4000, $clientHeight: 400 }, [
        el('div', { class: 'sidebar', $text: 'Recently viewed' }),
      ]),
    );
  }

  if (owner) children.push(...ownerMarkup(owner));

  return { document: createDocument(children), scroller, rows };
}

/**
 * The wishlist page as it was before the rewrite.
 *
 * @param {{ rows?: Array<{ appId: number, title: string, top: number, dlc?: boolean }>,
 *           scrollHeight?: number, clientHeight?: number }} [options]
 * @returns {{ document: object, scroller: object, rows: object[] }}
 */
export function oldLayout({
  rows = [
    { appId: 440, title: 'Team Fortress 2', top: 0 },
    { appId: 570, title: 'Dota 2', top: 208 },
    { appId: 730, title: 'Counter-Strike 2', top: 104 },
  ],
  scrollHeight = 3200,
  clientHeight = 800,
} = {}) {
  const elements = rows.map((row) =>
    el(
      'div',
      {
        class: 'wishlist_row',
        id: `wishlist_row_${row.appId}`,
        'data-app-id': String(row.appId),
        $top: row.top,
        $height: 104,
      },
      [
        el('img', {
          class: 'capsule',
          src: `https://cdn.akamai.steamstatic.com/steam/apps/${row.appId}/capsule_sm_120.jpg`,
          alt: row.title,
        }),
        el('a', { class: 'title', href: `/app/${row.appId}/` }, [el('span', { $text: row.title })]),
        ...(row.dlc ? [el('div', { class: 'dlc_flag', $text: 'DLC' })] : []),
      ],
    ),
  );

  const scroller = el(
    'div',
    { id: 'wishlist_ctn', $scrollHeight: scrollHeight, $clientHeight: clientHeight },
    elements,
  );

  return {
    document: createDocument([
      el('div', { id: 'wishlist_count', $text: `${rows.length} games on your wishlist` }),
      scroller,
    ]),
    scroller,
    rows: elements,
  };
}
